/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interficie;

import dades.BD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import logica.Usuari;
import logica.Utils;
import logica.log.Log;

/**
 *
 * @author oscar
 */
public class FLogin extends JFrame implements ActionListener{
    private static Usuari usuari;
    public FLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void mostrarFrame(){
        btnEntrar.addActionListener(this);
        btnAlta.addActionListener(this);
        btnRanking.addActionListener(this);
        btnSortir.addActionListener(this);
        lblAvis.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FLogin.this.setVisible(true);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUSUARI = new javax.swing.JLabel();
        lblPASSWORD = new javax.swing.JLabel();
        txtUsuari = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnSortir = new javax.swing.JButton();
        lblAvis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        lblUSUARI.setText("Usuari");

        lblPASSWORD.setText("Password");

        txtUsuari.setText("kobe24");

        txtPassword.setText("bryant24");

        btnEntrar.setText("Entrar");

        btnAlta.setText("Alta");

        btnRanking.setText("Ranking");

        btnSortir.setText("Sortir");

        lblAvis.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAvis.setForeground(new java.awt.Color(255, 0, 51));
        lblAvis.setText("Avis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRanking, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(btnSortir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPASSWORD)
                            .addComponent(lblUSUARI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuari)
                            .addComponent(txtPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvis)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUSUARI)
                    .addComponent(txtUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPASSWORD)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRanking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSortir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnSortir;
    private javax.swing.JLabel lblAvis;
    private javax.swing.JLabel lblPASSWORD;
    private javax.swing.JLabel lblUSUARI;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuari;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource()==btnRanking) {
            setTitle("boto ranking");
            new FRanking().mostrarFrame();
        }
        else if (e.getSource()==btnEntrar) {
            String usu = txtUsuari.getText();
            String password = new String(txtPassword.getPassword());
            if(usu.length() > 0 && password.length() > 0){
                password = Utils.codificarCadena(password);
                usuari = BD.obtenirUsuari(usu, password);
                if(usuari != null){
                    lblAvis.setVisible(false);
                    txtPassword.setText(null);
                    txtUsuari.setText(null);
                    new FMenu().mostrarFrame();
                    dispose();
                }
                else{
                    lblAvis.setText("Usuari o password incorrecte");
                    lblAvis.setVisible(true);
                    Log log = Log.getInstance(FLogin.class);
                    log.afegirError("Usuari o password incorrecte");
                }
            }
            else{
                lblAvis.setText("Falta usuari o password");
                lblAvis.setVisible(true);
                Log log = Log.getInstance(FLogin.class);
                log.afegirError("Falta usuari o password");
            }
        }
        else if (e.getSource()==btnAlta) {
            new FAlta().mostrarFrame();
        } 
        else if (e.getSource() == btnSortir){
            dispose();
            System.exit(0);
        }
    }
    
    public static Usuari obtenirUsuari(){
        return usuari;
    }
}
